/**
 * Emits Supabase seed.sql from the TS checklist + vendor + user modules.
 * Run with: pnpm --filter @vo360/checklists build:sql
 *
 * Auth users (passwords) are out of scope — seed only public.users with the
 * same UUIDs you create via Supabase Auth.
 */
import { TEMPLATES, VENDORS, DEMO_USERS } from '../src';

const sql = (s: string) => s.replace(/'/g, "''");

function emit(): string {
  const out: string[] = [];
  out.push('-- Generated by packages/checklists/scripts/emit-seed-sql.ts');
  out.push('-- Do not edit by hand — run `pnpm --filter @vo360/checklists build:sql` to regenerate.');
  out.push('');

  out.push('-- Users (mirror of auth.users — populate auth separately)');
  for (const u of DEMO_USERS) {
    out.push(
      `insert into public.users (id, email, name, role) values ('${u.id}', '${sql(u.email)}', '${sql(u.name)}', '${u.role}') on conflict (id) do nothing;`,
    );
  }
  out.push('');

  out.push('-- Vendors');
  for (const v of VENDORS) {
    out.push(
      `insert into public.vendors (id, name, type, address, contact_name, contact_phone) values ('${v.id}', '${sql(v.name)}', '${sql(v.type)}', '${sql(v.address)}', ${v.contactName ? `'${sql(v.contactName)}'` : 'null'}, ${v.contactPhone ? `'${sql(v.contactPhone)}'` : 'null'}) on conflict (id) do nothing;`,
    );
  }
  out.push('');

  out.push('-- Checklist templates / sections / questions');
  for (const t of TEMPLATES) {
    out.push(
      `insert into public.checklist_templates (id, name, industry, version, is_active) values ('${t.id}', '${sql(t.name)}', '${t.industry}', ${t.version}, ${t.isActive}) on conflict (id) do nothing;`,
    );
    for (const s of t.sections) {
      out.push(
        `insert into public.checklist_sections (id, template_id, name, display_order) values ('${s.id}', '${t.id}', '${sql(s.name)}', ${s.order}) on conflict (id) do nothing;`,
      );
      for (const q of s.questions) {
        const opts = JSON.stringify(q.responseOptions);
        out.push(
          `insert into public.checklist_questions (id, section_id, text, is_mandatory, response_options, display_order) values ('${q.id}', '${s.id}', '${sql(q.text)}', ${q.isMandatory}, '${opts}'::jsonb, ${q.order}) on conflict (id) do nothing;`,
        );
      }
    }
  }
  out.push('');

  out.push('-- Default verdict lexicon (from @vo360/shared DEFAULT_LEXICON)');
  out.push(
    `insert into public.lexicon (verdict, keywords) values ` +
      [
        ['majorly_comply', ['majorly comply', 'fully comply', 'comply', 'complies', 'compliant', 'meets', 'passes', 'good', 'okay', 'fine', 'no issues', 'all good', 'satisfactory', 'approved', 'pass']],
        ['partial_comply', ['partial comply', 'partial compliance', 'partially', 'partial', 'somewhat', 'mostly but', 'kind of', 'sort of', 'almost', 'half comply']],
        ['not_complied', ['not comply', 'does not comply', 'fails', 'failed', 'fail', 'non-compliant', 'not compliant', 'issue', 'problem', 'violation', 'bad', 'rejected', 'reject', 'unsatisfactory']],
        ['na', ['not applicable', "doesn't apply", 'does not apply', 'skip', 'not relevant', 'not required', 'n a', 'na']],
      ]
        .map(([v, kw]) => `('${v}', '${JSON.stringify(kw)}'::jsonb)`)
        .join(', ') +
      ` on conflict (verdict) do update set keywords = excluded.keywords, updated_at = now();`,
  );

  return out.join('\n') + '\n';
}

process.stdout.write(emit());
