import type { AuditResponse, AuditStatus, Utterance, Verdict } from './types';

export type MutationType =
  | 'audit.start'
  | 'audit.update_status'
  | 'audit.submit'
  | 'response.upsert'
  | 'photo.attach'
  | 'transcript.append';

export interface MutationBase {
  /** UUID generated by the client; used for idempotency on the server. */
  clientMutationId: string;
  type: MutationType;
  occurredAt: string;
}

export interface AuditStartMutation extends MutationBase {
  type: 'audit.start';
  payload: { auditId: string };
}

export interface AuditUpdateStatusMutation extends MutationBase {
  type: 'audit.update_status';
  payload: { auditId: string; status: AuditStatus };
}

export interface AuditSubmitMutation extends MutationBase {
  type: 'audit.submit';
  payload: { auditId: string };
}

export interface ResponseUpsertMutation extends MutationBase {
  type: 'response.upsert';
  payload: {
    responseId: string;
    auditId: string;
    questionId: string;
    verdict?: Verdict;
    comment?: string;
    confidence?: number;
    source: 'tap' | 'voice';
  };
}

export interface PhotoAttachMutation extends MutationBase {
  type: 'photo.attach';
  payload: { photoId: string; responseId: string; storagePath: string };
}

export interface TranscriptAppendMutation extends MutationBase {
  type: 'transcript.append';
  payload: { auditId: string; utterances: Utterance[] };
}

export type ClientMutation =
  | AuditStartMutation
  | AuditUpdateStatusMutation
  | AuditSubmitMutation
  | ResponseUpsertMutation
  | PhotoAttachMutation
  | TranscriptAppendMutation;

export interface SyncRequest {
  mutations: ClientMutation[];
}

export interface SyncMutationResult {
  clientMutationId: string;
  status: 'applied' | 'duplicate' | 'error';
  message?: string;
}

export interface SyncResponse {
  results: SyncMutationResult[];
  serverTime: string;
  /** Authoritative response state for affected audits, so client can reconcile. */
  responses?: AuditResponse[];
}
